---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
suites:
  - name: from_repo
    run_list:
      - recipe[install-redis::default]
      - recipe[install-redis::from-repository]
      - recipe[install-redis::server]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
  - name: from_package
    run_list:
      - recipe[install-redis::default]
      - recipe[install-redis::from-package
      - recipe[install-redis::server]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:    
