source 'https://rubygems.org'

gem 'chefspec', '~> 4.5'
gem 'guard'
gem 'guard-rspec'
gem 'berkshelf'
gem 'inspec'
gem 'rake'
group :integration do
  gem 'test-kitchen', '~> 1.2'
  gem 'kitchen-inspec'
end
group :vagrant do
  gem 'vagrant-wrapper', '~> 2.0'
  gem 'kitchen-vagrant', '~> 0.18'
end
